--- #YAML:1.0
name:               Net-Frame
version:            1.07
abstract:           the base framework for frame crafting
author:
    - GomoR <gomor-cpan_at_gomor.org>
license:            artistic
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Bit::Vector:    0
    Class::Gomor:   1.00
    Net::IPv6Addr:  0
    Socket6:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
