--- #YAML:1.0
name:                Net-Frame
version:             1.00_03
abstract:            the base framework for frame crafting
license:             Artistic
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Bit::Vector:                   0
    Class::Gomor:                  1.00
    Net::IPv6Addr:                 0
    Net::Libdnet:                  0
    Socket6:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - GomoR <perl@gomor.org>
